Update description in manifest
blockstack/blockstack-app pull request #1681
Opened 2021-09-03 16:47 UTC by markmhx

This "modernizes" our description for Stacks 2.0:

"Hiro Wallet is a safe way to manage your STX, sign into decentralized apps, and protect your funds while interacting with Clarity smart contracts."

2021-09-07 06:28 UTC, beguene approved these changes

2021-09-07 08:19 UTC, kyranjamie requested changes
https://developer.chrome.com/docs/extensions/mv2/manifest/description/

> A plain text string (no HTML or other formatting; no more than 132 characters)

2021-09-07 11:10 UTC, kyranjamie commented
Lastly, are we sure we want the full stop?

2021-09-07 12:03 UTC, markmhx commented
I figure it's best since it displays in UIs as a sentence such as here in the Chrome Web Store:

![image](https://user-images.githubusercontent.com/28991/132341379-6f125f84-e16f-447b-9db3-3ac67408669b.png)

2021-09-07 13:10 UTC, fbwoolf approved these changes

2021-09-08 15:12 UTC, kyranjamie approved these changes

2021-09-09 14:01 UTC, merged