Encourage users to onboard via the full page mode
blockstack/blockstack-app pull request #2266
Opened 2022-02-24 16:55 UTC by kyranjamie

Much like Metamask, it's better to encourage users to onboard via the full screen mode. Consider https://github.com/hirosystems/stacks-wallet-web/issues/2191, the user wants to use a password manager but they have to deal with opening/closing the popup.

We _could_ send them straight to back up secret key page (a bit more work), but even just opening the whole page full screen is an improvement imo. 

https://user-images.githubusercontent.com/1618764/155570365-4483be9e-0c98-49e8-9080-edb7c92ed6b4.mp4

2022-02-24 20:35 UTC, fbwoolf commented
I like this idea ...can clicking on `Create Stacks Account` in the popup go to the next page route in full page (BackUpSecretKey) rather than having to repeat clicking on the action? Also, we would do the same for clicking on `Sign in with Secret Key`?

2022-02-25 01:38 UTC, andresgalante commented
I don't know if I am fully onboard with this idea, but I'd like @landitus and @markmhx opinion.

Let's say a user creates their account with 1passowrd in full screen mode. Then they lock their wallet. The next time they want to unlock it would, they also have to be redirected to the full screen page. Else they wouldn't be able to unlock it with their password app.

Unless I am missing something, if we do this move, then we should eliminate any unlock, login or creating account interaction from the extension experience and always redirect users to the full page view.


<img width="426" alt="Screen Shot 2022-02-24 at 22 38 01" src="https://user-images.githubusercontent.com/1832037/155637105-87e873a7-bc91-405d-8032-8ac76a37ea33.png">

2022-02-25 09:08 UTC, kyranjamie commented
> can clicking on Create Stacks Account in the popup go to the next page route in full page (BackUpSecretKey)

It could, yes, I considered this. Though I can't help but feel people will click "Create STX account" without necessarily reading, and maybe they'll want to use a Ledger, for example. Maybe we should change that label. We could also not open the pop up at all and only open the new tab (like MM).

2022-02-25 11:27 UTC, andresgalante commented
You are right Kyran, I was missing something. I thought that 1 password would work on full page and not on extension view.

In this case, I am 👍 for trying this

2022-02-25 14:40 UTC, landitus commented
This is a good idea as it eases the pain of using a password manager and also re-inforces the current behavior after installing the extension. I like it.

> can clicking on Create Stacks Account in the popup go to the next page route in the full page (BackUpSecretKey) rather than having to repeat clicking on the action? 

For some reason going from the popup to backup keys in full-screen step feels disconnected to me. Probably it would need some further copy or design change.

Looking at the video, I think repeating the same screen in two sizes feels "buggy" cause the user already clicked on the same button. 

> We could also not open the pop-up at all and only open the new tab (like MM). (Just for the onboarding flow)

☝️ I'd favor this solution over the other, as I believe it's a better UX than having to see the same screen twice. I've seen extensions that launch to full screen and it's a natural approach. 

**Question:** would this change affect the onboarding triggered as a pop-up from applications?
<img width="1512" alt="Screenshot 2022-02-25 at 15 36 18" src="https://user-images.githubusercontent.com/239215/155733830-eb17b0ec-4ed8-4ce0-af9d-07784e3857ed.png">

2022-02-27 14:40 UTC, markmhx commented
I like the idea of sending users through onboarding via a full-width viewport, but isn't this already the case given how installations work with extension stores?

https://user-images.githubusercontent.com/28991/155886890-5f3d1b54-05f4-4ef0-ae90-3a18c032101d.mov

2022-02-27 15:14 UTC, kyranjamie commented
> but isn't this already the case given how installations work with extension stores?

Yep, exactly. This just enforces it for the other circumstances where you might set up your wallet. Such as:
- Not creating a wallet immediately after install and returning later
- Signing out of a wallet and going through the onboarding flow again

2022-02-27 17:47 UTC, markmhx commented
> We could also not open the pop-up at all and only open the new tab (like MM). (Just for the onboarding flow)
> 
> ☝️ I'd favor this solution over the others, as I believe it's a better UX than having to see the same screen twice. I've seen extensions that launch to full screen and it's a natural approach.

I'm in favor of this approach as well if we want to address those other cases. It's best to avoid having the user see the same screen twice, especially after they've already selected the CTA.

2022-03-02 09:51 UTC, kyranjamie commented
Understand the drive to not repeat content. I looked into getting it to auto-open the full page mode if you have no account, showing no popup. It's more involved than I'd like to tackle right now. 

As an alternative, I suggest we alter the content in pop up mode, to be a more generic "Get started" action, and their decision to go software/ledger is made on the full screen mode. No content repetition. Something along the lines of:

<details>
<summary>Outdated screenshot</summary>


![image](https://user-images.githubusercontent.com/1618764/156338260-4ce163a1-1e9f-4ce9-9984-f2d8eb7c1af9.png)

</details>



I reckon this is a better solution. Auto-opening a full screen mode is a [surprising/unexpected behaviour](https://www.nngroup.com/articles/efficiency-vs-expectations/).

@markmhx @landitus

2022-03-02 10:15 UTC, markmhx commented
How would this proposed solution work for when an extension store automatically opens this page post-installation for nearly all new users? They'd see a "Get started with Stacks" version of this screen then a "Create Stacks Account" one once clicking, both in full-screen?

Presumably we can't avoid that behavior since the same initial index appears automatically in either the popup or full-screen, depending on whether the user arrives post-installation or comes back later and re-opens to onboard.

I'm hesitant to over-invest polish for this current flow since @landitus and I have begun talking about how we may revamp the onboarding UX in general. I'll create a project brief soon that captures the current thinking on that front, but basically this screen may go away entirely.

2022-03-02 10:46 UTC, kyranjamie commented
> They'd see a "Get started with Stacks" version of this screen then a "Create Stacks Account" one once clicking, both in full-screen?

No. They'd see the normal full screen welcome page, exactly the same as it is now. The "Get started" is only on the popup.

> Presumably we can't avoid that behavior since the same initial index appears automatically in either the popup or full-screen, depending on whether the user arrives post-installation or comes back later and re-opens to onboard.

Not sure I follow, but hopefully first point clears up that concern. 

Agree on not over polishing; but this work is already done, improves onboarding as is, and fixes an issue.

2022-03-02 10:59 UTC, markmhx commented
If that's the case, I'm okay with this change if @landitus is.

2022-03-02 14:25 UTC, kyranjamie commented
Spoke with @landitus and we've come up with a solution, that's still an improvement pre-full homepage redesign. Users are not forced (in ignorance) to sign up in popup mode.

Content is different so there's no repetition. `user_initiated_onboarding_from_popup_mode` is fired when triggered via pop up (which we expect to be the exceptional case).

<details>
<summary>Outdated screenshot</summary>

![image](https://user-images.githubusercontent.com/1618764/156380039-e600ad72-a4bd-42a1-a555-f9dae12d59c9.png)

</details>



cc/ @markmhx

2022-03-02 15:08 UTC, landitus commented
Thanks @kyranjamie. I wanted to try some alternative copy and get some quick feedback cc/ @markmhx. What about:

- heading: Welcome to Hiro Wallet
- paragraph: same
- CTA: Get started

![Frame 1](https://user-images.githubusercontent.com/239215/156388652-c4489389-4a66-4fd2-98ff-c88359efb804.png)

2022-03-02 18:07 UTC, markmhx commented
Looks good, just a minor tweak: "Welcome to Hiro Wallet" for header instead of "Welcome to _the_ Hiro Wallet"

2022-03-03 11:43 UTC, kyranjamie commented
![image](https://user-images.githubusercontent.com/1618764/156558258-b5a34183-f6fc-453e-913b-45eb0561576e.png)

Added a line break, otherwise Hiro Wallet is on two lines.

2022-03-03 11:50 UTC, andresgalante commented
Are extensions different browsers always the same width? else I rather let the content accommodate itself than have a line break

2022-03-03 11:56 UTC, markmhx commented
A way to ensure they're always on the same line but not worry about varying widths is placing `&nbsp` between the words.

2022-03-03 11:57 UTC, kyranjamie commented
> Are extensions different browsers always the same width? else I rather let the content accommodate itself than have a line break

It's the same width in all browsers and doesn't ever resize

2022-03-03 21:09 UTC, landitus commented
Thanks @kyranjamie. The screen itself looks good to me.

I did find an issue when testing it. If you go to an app, say https://stxnft.com/, if you start the onboarding through Connect, this new screen appears and forces the user to onboard in a new tab. As is, it degrades the Connect flow, taking the user out of the app's context. Also, the Connect modal gets out of sync and the wallet connection never completes (unless you reload the app). I guess this behaviour wasn't intended with this change.

<img width="1312" alt="Screenshot 2022-03-03 at 21 55 41" src="https://user-images.githubusercontent.com/239215/156651865-17fb7a43-c01a-445a-8e7a-ceaba57b361d.png">
<img width="1311" alt="Screenshot 2022-03-03 at 21 55 55" src="https://user-images.githubusercontent.com/239215/156651878-8295aadb-20cb-4a7d-8dbd-27e4968573a5.png">

2022-03-03 21:10 UTC, landitus requested changes
Feedback submitted

2022-05-18 12:42 UTC, kyranjamie commented
Closing in favour of this working merging along side Ledger

2022-05-18 12:42 UTC, closed without merging