feat: add moonpay fiat onramp
blockstack/blockstack-app pull request #2312
Opened 2022-03-18 11:00 UTC by beguene

closes #2068

2022-03-18 13:13 UTC, fbwoolf approved these changes
Nice!

2022-03-18 13:14 UTC, fbwoolf commented
I just realized this is in `Draft` mode, sorry I reviewed.

2022-03-18 13:29 UTC, beguene commented
@fbwoolf No this is great, thanks for the review. I placed it in draft so we don't merge it.

2022-03-18 14:52 UTC, landitus requested changes, later dismissed
👋 I've noticed some visual bugs, mostly regarding the page layout:

1. The page is missing it's top margin (regression)
2. The page is missing it's bottom margin, noticiable when scrolling down (regression)
3. This was already happening, but just noticed the layout works different here than in other sections. It seems the content is being centered vertically, which doesn't give a good result when reducing the viewport vertically. Note that some other pages have a better experience, such as **Send**.

<img width="1121" alt="Screenshot 2022-03-18 at 15 35 39" src="https://user-images.githubusercontent.com/239215/159024601-9d8a6de0-4a5b-4ebc-9a73-44b4cff36d46.png">
<img width="1512" alt="Screenshot 2022-03-18 at 15 38 23" src="https://user-images.githubusercontent.com/239215/159024583-15ac6876-9051-4fca-afaf-bc88895de913.png">
<img width="1080" alt="Screenshot 2022-03-18 at 15 47 34" src="https://user-images.githubusercontent.com/239215/159025885-ccc80945-d803-4990-a943-690dc4693a15.png">

2022-03-21 13:50 UTC, timstackblock commented
I do not see STX listed in the asset list on moonpay

<img width="1200" alt="Screen Shot 2022-03-21 at 9 49 39 AM" src="https://user-images.githubusercontent.com/49165468/159275059-08d0cd40-08f8-4ab2-b4f8-dcba384903c0.png">

2022-03-21 14:32 UTC, landitus commented
As @fbwoolf has been improving the responsiveness of the app in a separate PR, the first step would be to review this https://github.com/hirosystems/stacks-wallet-web/pull/2277 and check if the visual bugs are fixed there.

2022-03-21 14:40 UTC, landitus commented
I can confirm that https://github.com/hirosystems/stacks-wallet-web/pull/2277 fixes the visual bugs I've found above. I've tested by adding more content and the margins and scrolls work as they should. cc/ @fbwoolf 

https://user-images.githubusercontent.com/239215/159284823-e351550f-d9d6-44d3-8d88-095c8e713e5a.mp4

2022-03-21 15:17 UTC, Eshwari007 commented
Couple of Test Findings:

1- The asset STX is not to be found in Moonpay as indicated by @timstackblock above
2- When the user selects a USDC coin (or any ETH based token) and  if the user has Metamask installed, the user is directed to Metamask
3- When the user removes Metamask from the ext and selects the USDC coin, the user receives 'Enter wallet address "page view
4. Am aware that we don't have a backward arrow to go back to Hiro wallet when the user selects the fiats on-ramp such as Transak, Moonpay, and Okcoin but believe we have a ticket for it which will ease user interface cc @markmhx 
5. Only on Okcoin integration, we have a Hiro page link header while we don't have it for Transak nor Moonpay, for consistency wise-would think it good to have Hiro page link on Moonpay and Transak as well.

cc @markmhx @beguene @timstackblock @andresgalante 
Attaching screen recordings and screenshots of the findings above.



https://user-images.githubusercontent.com/38872890/159292430-6090c5eb-5681-4cdb-909d-1efe0e2850b4.mov

<img width="314" alt="Screen Shot 2022-03-21 at 11 08 14 AM" src="https://user-images.githubusercontent.com/38872890/159292553-455c3b51-e91d-4639-8d96-fd7d59b42994.png">

2022-03-22 10:49 UTC, markmhx commented
There's no need to QA this PR until Moonpay has released support for Stacks.

2022-03-22 14:57 UTC, andresgalante commented
@landitus to create the video and send it to moonpay

2022-03-23 16:59 UTC, fbwoolf commented
I rebased this on the new home page work and changed the base branch. That PR should be merged prior to this.

2022-03-23 17:55 UTC, fbwoolf commented
@landitus once you unblock this, I can merge it into dev and create a new release PR.

2022-03-23 19:32 UTC, landitus commented
There's one last change we discussed with @markmhx. We'd like to switch the order of the providers on the **Fund account** page. The new order should be:

1. Moonpay
2. Okcoin
3. Transak

2022-03-23 19:37 UTC, fbwoolf commented
> There's one last change we discussed with @markmhx. We'd like to switch the order of the providers on the **Fund account** page. The new order should be:
> 
> 1. Moonpay
> 2. Okcoin
> 3. Transak

Ok, np, I'll update the order. 👍

2022-03-23 19:48 UTC, fbwoolf commented on src/app/query/hiro-config/hiro-config.query.ts
> +const GITHUB_PRIMARY_BRANCH = 'feat/add-moonpay/I2068'; // TO CHANGE main
Don't forget to change this before merging.

2022-03-23 21:06 UTC, fbwoolf commented
@landitus I switched the order on these but was looking at the title and seems really big on this page in comparison to other logged in pages (ex. View Secret Key). Then I realized there is an issue to update the design on this page which has it has 2 columns (like the logged out onboarding), is this something we want to update now or are we rethinking this page? https://github.com/hirosystems/stacks-wallet-web/issues/2107

2022-03-24 12:31 UTC, markmhx commented
MoonPay is saying we can and should pass the wallet address as a GET parameter (`walletAddress`) even though we can't server-side sign it since they'll whitelist it for release (and as such, we don't need to sign it after all).

@fbwoolf can you add this to the integration even if it breaks the flow temporarily (before they end up whitelisting)?

2022-03-24 12:47 UTC, landitus commented
> is this something we want to update now or are we rethinking this page?

I noticed the new designs and I believe we should review them first. I'm thinking of adding this as a new issue for a future enhancement.

2022-03-24 12:57 UTC, markmhx commented
Let's also replace our linking to MoonPay's staging / sandbox site with their production one for development builds (since we can't test effectively on their staging site anyway for lack of STX listing there).

2022-03-24 13:01 UTC, markmhx commented
A nitpik to fix that I just noticed: It's "MoonPay" (capitalized "P") not "Moonpay"

2022-03-24 18:11 UTC, markmhx commented
Link works for me now during testing!

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/28991/159982661-40ef3b66-b2fb-42ce-812b-f70d32eb7766.png">

I had to update our admin settings to enable "STX" and disable all other tokens 🤦

2022-03-24 18:53 UTC, merged