Release/2022 05 31 lazy lion
blockstack/blockstack-app pull request #2468
Opened 2022-05-31 14:30 UTC by fbwoolf

Contents:

- https://github.com/hirosystems/stacks-wallet-web/issues/2425
- https://github.com/hirosystems/stacks-wallet-web/issues/2422
- https://github.com/hirosystems/stacks-wallet-web/issues/2251
- https://github.com/hirosystems/stacks-wallet-web/issues/2423
- https://github.com/hirosystems/stacks-wallet-web/issues/1800

cc/ @kyranjamie @fbwoolf @beguene @He1DAr

2022-05-31 16:50 UTC, landitus commented
@fbwoolf I found a smallish issue when testing the dev build, nothing critical at all. There's an unnecessary scroll on the new Receive page (on the widget extension). Probably you can get rid of some bottom margin/padding that's not necessary.

![CleanShot 2022-05-31 at 17 12 11@2x](https://user-images.githubusercontent.com/239215/171229793-cc4186ef-5801-449c-89f9-02a27f6eecec.png)

2022-05-31 16:57 UTC, fbwoolf commented
> @fbwoolf I found a smallish issue when testing the dev build, nothing critical at all. There's an unnecessary scroll on the new Receive page (on the widget extension). Probably we can get rid of some bottom margin/padding that's not necessary.
> 
Ok, yep, I'll fix it before we release. Thx!

2022-05-31 17:00 UTC, fbwoolf commented
To make a note on this, we need to make sure to update the hiro-config here (to path 'main') and the new fund page copy/links need to be finalized by @markmhx so we can update the code here before releasing.

2022-05-31 23:28 UTC, fbwoolf commented
@timstackblock the receive page scroll that was mentioned here has been fixed on the new build. I also merged in another fixed issue that I added to the description. You will need to download the latest build to test it. Thx.

2022-06-01 09:58 UTC, kyranjamie requested changes
I think there's a critical bug in this release, causing white screen on the wallet homepage. 

**To replicate**
- Checkout latest release tag
- Create software wallet
- Checkout `dev`, rebuild/refresh wallet
- Sign in, expect whitescreen
- 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/1618764/171379151-eedc6f25-6bc5-4eb2-91c4-4ee268ea66f5.png">

2022-06-01 10:27 UTC, fbwoolf commented
> I think there's a critical bug in this release, causing white screen on the wallet homepage.
> 
> **To replicate**
> 
> * Checkout latest release tag
> * Create software wallet
> * Checkout `dev`, rebuild/refresh wallet
> * Sign in, expect whitescreen
> 
> <img alt="image" width="756" src="https://user-images.githubusercontent.com/1618764/171379151-eedc6f25-6bc5-4eb2-91c4-4ee268ea66f5.png">

Ok, thanks, I'll take a look this morning and fix ...might just have to do with some of my renaming of all the onboarding step stuff. I thought I saw this locally and just had to quit my running process and rebuild.

2022-06-01 12:40 UTC, fbwoolf commented
~~@kyranjamie I don't see that issue using the build version here, so I'm thinking what you saw was just a build issue with renaming? I saw it too before I killed my process and rebuilt. @timstackblock let me know if you run into the issue.~~

2022-06-01 13:00 UTC, kyranjamie commented
The issue is likely with the upgrade path, if you create new versions each time, you won't see the issue. Possibly same issue reported [on Discord](https://discord.com/channels/621759717756370964/745197302255321108/981542148929384470)

2022-06-01 14:52 UTC, fbwoolf commented
PR is up for proposed fix here: https://github.com/hirosystems/stacks-wallet-web/pull/2471

2022-06-02 17:57 UTC, fbwoolf commented on src/app/query/hiro-config/hiro-config.query.ts
> +const GITHUB_PRIMARY_BRANCH = 'dev';
Make sure to change this back to 'main' before merging.

2022-06-02 17:58 UTC, fbwoolf commented on src/app/pages/fund/components/fiat-providers.utils.ts
> +  return `https://hiro.so/wallet-faq/exchange-purchase?provider=${provider}&address=${address}`;
Make sure this link has content before merging.

2022-06-09 17:09 UTC, fbwoolf commented
@kyranjamie @landitus I want to confirm the persisted state here on skipping the fund account page. Do we want it to be persisted? So, it doesn't show again when creating a new wallet or on refresh? I implemented it that way, but I want to verify it is what we want now that I know changing persisted state is not ideal.

Right now, if a user skips the fund page > signs out > creates a new wallet > they won't see the fund page again. They will only see it again on a fresh install of the extension. If we don't persist it, then on refreshing the home page (with a 0 STX balance) the fund page will show again and the user will have to skip it each time.

Removing the persisted state is easy, I just want to do it before it goes live if we feel it is a better starting point.

2022-06-10 12:34 UTC, kyranjamie commented
>  if a user skips the fund page > signs out > creates a new wallet > they won't see the fund page again

This should not be the behaviour imo. signing out = wipe everything. 

I don't think we need any state here at all? It's just routing (which can be conditional).

```mermaid
graph TD
    A(/get-started) --> B(/fund-account) -->|Skip| C(/home)
```

Think of the logic as:

> when onboarding complete, redirect to fund account page. The skip action = `navigate(RouteUrls.Home)` 

Rather than:

> On every homepage render, check if balance === 0, then redirect to fund account page

2022-06-10 12:57 UTC, fbwoolf commented
> 
> Rather than:
> 
> > On every homepage render, check if balance === 0, then redirect to fund account page
>
The original behavior requested was to force users back to the fund page (at least that is how I interpreted it). I agree it seems like too much (at least to start). I will change it so it is a simple routing when they skip it. They can always get there from the buy button on the home page.

2022-06-10 14:10 UTC, kyranjamie commented
> The original behavior requested was to force users back to the fund page (at least that is how I interpreted it).

It would be super annoying, bad ux, to auto-redirect back every time the user refreshes the page. +1 to this change, the routing solution is simpler build, and better for the user.

2022-06-12 16:15 UTC, fbwoolf commented
Path for wallet-config has been changed back to `main` here. Therefore, the new build won't work with the new fund page. This is ready to release.

2022-06-13 13:58 UTC, beguene approved these changes

2022-06-13 14:10 UTC, merged