feat: increase unused taproot address search range
blockstack/blockstack-app pull request #3323
Opened 2023-03-01 12:08 UTC by edu-stx

Closes #3297

2023-03-01 13:49 UTC, kyranjamie requested changes
Mark's suggestion of 50 doesn't consider the cost of firing so many requests. Let's revert to 20 or something, but 50 doesn't make sense.

2023-03-01 22:21 UTC, markmhx commented
Note my comment here about perhaps finding a more customizable option: https://github.com/hirosystems/stacks-wallet-web/issues/3297#issuecomment-1450930897

However, if we can proceed with a quick bump from 5 to 20, that'll should help on the margin.

2023-03-02 12:31 UTC, edu-stx commented
Sounds good, bumping to 20 until we find a better solution

2023-03-02 15:52 UTC, kyranjamie approved these changes

2023-03-02 16:41 UTC, merged