fix(popup): avatar circle on stacks transactions
blockstack/blockstack-app pull request #4527
Opened 2023-11-16 08:35 UTC by edgarkhanzadian

Addresses #4472 

#### Bug description

The issue is coming from useCurrentStacksAccount hook. So for the account name (that "Account <number>" title) we’re using the useCurrentAccountDisplayName hook that simply uses useCurrentAccountIndex hook that in most cases just reads default current account index. 

In case of the account circle, we use useCurrentStacksAccount hook, that utilizes 2 hooks to decide on the account index. One is useCurrentAccountIndex (that is most probably a default current account index) and the other one is useTransactionAccountIndex. Now useTransactionAccountIndex searches stxAddress in txPayload, and if finds one, tries to find an account with that stxAddress. It finds one in another account and returns that another account.

Thus the issue only happens when we sign stacks transactions.

Now, to fix the issue with the account circle i would just use useCurrentAccountIndex together with useStacksAccounts to make the account circle consistent with the name. But the logic behind useCurrentStacksAccount still seems wrong to me 🤔 It is probably going to breed more bugs if we don't refactor it (decouple stx logic from non-stx logic)

## UI test

#### Reproduced bug

https://github.com/leather-wallet/extension/assets/22010816/d6ccffff-59da-45c7-8804-0b8eda233bda

#### Fixed bug

https://github.com/leather-wallet/extension/assets/22010816/6ed42b17-33e4-4a86-98e4-801c20ac02e7

2023-11-16 09:22 UTC, pete-watters requested changes
This code LGTM but playwright shard 1 is failing

2023-11-16 10:38 UTC, edgarkhanzadian commented
@pete-watters re-ran the job and it passes now. Probably related to: #4502

2023-11-16 13:16 UTC, kyranjamie commented
Thanks for taking this on @edgarkhanzadian, indeed you're highlighting some legitimate flaws in the design of the code. This relates to the differences in the implementation between the ["legacy" JWT-based stacks requests](https://github.com/leather-wallet/extension/blob/8c3f3d2535fc1da5292eef04c2b922b9985d6f83/src/inpage/inpage.ts#L82-L217), and the newer [`.request` API](https://github.com/leather-wallet/extension/blob/8c3f3d2535fc1da5292eef04c2b922b9985d6f83/src/inpage/inpage.ts#L230-L252) the wallet exposes.

`useCurrentStacksAccount` was written in a way where, for each request that can change the user's default address, we'd have to [add explicit clauses in this hook to check each one for a possible account index](https://github.com/leather-wallet/extension/blob/8c3f3d2535fc1da5292eef04c2b922b9985d6f83/src/app/store/accounts/blockchain/stacks/stacks-account.hooks.ts#L27-L29). This isn't very easy to maintain as it's easily forgotten and requires this hook to be aware of unrelated implementation details.

With the `.request` methods, we use `URLSearchParams` to pass generic request-agnostic info [(e.g. account index on `signPsbt`)](https://github.com/leather-wallet/extension/blob/8c3f3d2535fc1da5292eef04c2b922b9985d6f83/src/background/messaging/rpc-methods/sign-psbt.ts#L73-L76) to the pop up, allowing requests to globally alter the app state

For now I think your current approach is okay, as we later aim to remove these APIs.

2023-11-16 13:55 UTC, edgarkhanzadian commented
@kyranjamie oof that's tough, thank you for a very detailed explanation ! I'll keep an eye on the differences of those 2 approaches in the code.

2023-11-17 08:08 UTC, kyranjamie commented on src/app/features/current-account/current-account-avatar.tsx
> +  const currentAccount = accounts[accountIndex] as StacksAccount | undefined;
In future this could come from the rootkey's fingerprint, so that it doesn't target any specific chain.

2023-11-17 15:19 UTC, fbwoolf approved these changes

2023-11-20 13:27 UTC, pete-watters approved these changes
👍

2023-11-27 16:31 UTC, merged