Release
blockstack/blockstack-app pull request #5176
Opened 2024-04-08 09:39 UTC by pete-watters

2024-04-08 09:45 UTC, pete-watters commented
Marking this as a draft as we need to disable or test chainalysis checks before releasing

2024-04-10 00:56 UTC, fbwoolf commented
If this is reset to dev head and will include swap routing changes, this needs to be included: https://github.com/leather-wallet/extension/pull/5195

2024-04-10 09:22 UTC, kyranjamie approved these changes

2024-04-10 09:26 UTC, alter-eggo requested changes
https://github.com/leather-wallet/extension/pull/5178 we need to merge it as well, there is 'no signer' bug fix

2024-04-10 13:27 UTC, alter-eggo approved these changes

2024-04-10 13:32 UTC, merged