feat: Enable event tracking
blockstack/blockstack-app pull request #58
Opened 2020-01-22 15:08 UTC by kyranjamie

Currently relies on an environment variable.

2020-01-23 01:13 UTC, hstove commented
Hm - why does the git diff include everything in `refactor/screen-template`? It makes it much harder to review. Is there something off with the diff here?

2020-01-23 09:50 UTC, kyranjamie commented
Fixed now — I had to `reset --hard refactor/screen-template` and cherry pick the commit back.

2020-01-23 16:19 UTC, aulneau approved these changes

2020-01-24 04:31 UTC, hstove requested changes
Very minor changes - then I'm happy to merge.

2020-01-24 04:31 UTC, hstove commented on webpack.config.js
> +      segmentHost: 'cdn.segment.io',
Instead of using them here, let's just add this to `DefinePlugin`. That way, we won't have to repeat this for each HTML target.

2020-01-24 04:53 UTC, hstove commented
Note - I updated this PR to use `DefinePlugin` - feel free to push back if you think it should be different!

2020-01-24 04:54 UTC, hstove approved these changes

2020-01-24 08:04 UTC, merged

2020-01-24 08:06 UTC, kyranjamie commented
No problem, co-author, looks better 

![image](https://user-images.githubusercontent.com/1618764/73053722-c8967780-3e88-11ea-9ae7-7906bc81c0ea.png)