fix: update support links and deprecate sentry feedback, closes #5813
blockstack/blockstack-app pull request #5842
Opened 2024-09-04 05:11 UTC by pete-watters

This PR updates the menu support links and deprecates Sentry feedback as per https://github.com/leather-io/extension/issues/5813

2024-09-04 07:46 UTC, alter-eggo commented on src/app/features/errors/app-error-boundary.tsx
> +import { LEATHER_SUPPORT_URL } from '@shared/constants';
this should be in mono no?

2024-09-04 08:26 UTC, pete-watters commented on src/app/features/errors/app-error-boundary.tsx
> +import { LEATHER_SUPPORT_URL } from '@shared/constants';
I added it here: https://github.com/leather-io/mono/pull/425 

It seems like we have double constants in the monorepo and in `constants` here so I will clean it up

2024-09-05 09:31 UTC, pete-watters commented on src/app/features/errors/app-error-boundary.tsx
> +import { LEATHER_SUPPORT_URL } from '@shared/constants';
@alter-eggo I've updated this, can you re-check please?

2024-09-09 06:03 UTC, pete-watters commented
@kyranjamie can you please review this when you have a chance?

2024-09-11 06:24 UTC, kyranjamie approved these changes
I thought this'd been merged already.

RIP Leather User Feedback 2023–2024 🪦

2024-09-11 07:36 UTC, pete-watters commented
> I thought this'd been merged already.
> 
> RIP Leather User Feedback 2023–2024 🪦

Thanks, yes RIP indeed. Maybe we can have it on `mobile`? Or discuss adding it back in

2024-09-19 12:23 UTC, markmhendrickson commented
Let's just make sure we set up Slack notifications sufficiently before merging, per [this thread](https://trustmachines.slack.com/archives/C0520G8J33M/p1726748552797499).

2024-09-19 13:40 UTC, pete-watters commented
> Let's just make sure we set up Slack notifications sufficiently before merging, per [this thread](https://trustmachines.slack.com/archives/C0520G8J33M/p1726748552797499).

Can you mark the PR as `Needs work` in case we forget. Then once Slack is setup we can re-approve + merge

2024-09-19 14:42 UTC, markmhendrickson requested changes
Awaiting Slack integration for Front

2024-10-10 12:30 UTC, markmhendrickson commented
I'm closing in favor of https://github.com/leather-io/extension/pull/5897 in the spirit of testing more iterative changes to our feedback form before replacing it entirely with the new contact page.

2024-10-10 12:30 UTC, closed without merging