Fix extension build instructions
blockstack/blockstack-app pull request #700
Opened 2020-12-08 00:20 UTC by markmhx

The instructions for building the extension from source are incorrect since `yarn` is instructed for installation inside of the package directory instead of the root directory. This PR fixes that issue while simplifying the build commands using npm scripts.

2020-12-09 16:51 UTC, hstove requested changes
I'm not sure why the `yarn.lock` has so many changes - that shouldn't happen for a PR with no dependency changes.

2020-12-09 16:51 UTC, hstove commented on packages/app/README.md
> +yarn run build:extension
`yarn run` is not needed - any script can be used. This is different than NPM btw, where you have to specify `run` for all non-standard scripts.

So, just `yarn build:connect-ui` and `yarn build:extension` work!

2020-12-09 17:17 UTC, markmhx commented
Should I nuke the yarn.lock and regenerate?

2020-12-10 13:34 UTC, hstove approved these changes
I updated to:

- Have `yarn build:connect-ui` run after running `yarn` inside the monorepo. This should help reduce the commonality of people running into the "unbuilt connect-ui" problem.
- Fixed yarn.lock stuff
- Updated Playwright - I had updated in Connect 2.0 to fix CI stuff, so this is the same thing
- Changed the README command to just be `yarn build:extension`

Thanks @markmhx for putting this together!

2020-12-10 14:06 UTC, merged